---
safeMode: false
tables:
- name: "nyctaxi"
  type: "TABLE"
  schema: "nuhibesimi_gmail"
  columns:
  - name: "vendor_id"
    typeName: "string"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 1000000000
    scale: 0
    precision: 1000000000
    columnProperties: []
    autoincrement: false
    nullable: true
    primaryKey: false
  - name: "pickup_datetime"
    typeName: "datetime"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 23
    scale: 6
    precision: 23
    columnProperties: []
    autoincrement: false
    nullable: true
    primaryKey: false
  - name: "dropoff_datetime"
    typeName: "datetime"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 23
    scale: 6
    precision: 23
    columnProperties: []
    autoincrement: false
    nullable: true
    primaryKey: false
  - name: "passenger_count"
    typeName: "integer"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 10
    scale: 0
    precision: 10
    columnProperties: []
    autoincrement: false
    nullable: true
    primaryKey: false
  - name: "trip_distance"
    typeName: "float"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 17
    scale: 17
    precision: 17
    columnProperties: []
    autoincrement: false
    nullable: true
    primaryKey: false
  - name: "pickup_longitude"
    typeName: "float"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 17
    scale: 17
    precision: 17
    columnProperties: []
    autoincrement: false
    nullable: true
    primaryKey: false
  - name: "pickup_latitude"
    typeName: "float"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 17
    scale: 17
    precision: 17
    columnProperties: []
    autoincrement: false
    nullable: true
    primaryKey: false
  - name: "rate_code_id"
    typeName: "integer"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 10
    scale: 0
    precision: 10
    columnProperties: []
    autoincrement: false
    nullable: true
    primaryKey: false
  - name: "store_and_fwd_flag"
    typeName: "string"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 1000000000
    scale: 0
    precision: 1000000000
    columnProperties: []
    autoincrement: false
    nullable: true
    primaryKey: false
  - name: "dropoff_longitude"
    typeName: "float"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 17
    scale: 17
    precision: 17
    columnProperties: []
    autoincrement: false
    nullable: true
    primaryKey: false
  - name: "dropoff_latitude"
    typeName: "float"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 17
    scale: 17
    precision: 17
    columnProperties: []
    autoincrement: false
    nullable: true
    primaryKey: false
  - name: "payment_type"
    typeName: "string"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 1000000000
    scale: 0
    precision: 1000000000
    columnProperties: []
    autoincrement: false
    nullable: true
    primaryKey: false
  - name: "fare_amount"
    typeName: "float"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 17
    scale: 17
    precision: 17
    columnProperties: []
    autoincrement: false
    nullable: true
    primaryKey: false
  - name: "surcharge"
    typeName: "float"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 17
    scale: 17
    precision: 17
    columnProperties: []
    autoincrement: false
    nullable: true
    primaryKey: false
  - name: "mta_tax"
    typeName: "float"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 17
    scale: 17
    precision: 17
    columnProperties: []
    autoincrement: false
    nullable: true
    primaryKey: false
  - name: "tip_amount"
    typeName: "float"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 17
    scale: 17
    precision: 17
    columnProperties: []
    autoincrement: false
    nullable: true
    primaryKey: false
  - name: "tolls_amount"
    typeName: "float"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 17
    scale: 17
    precision: 17
    columnProperties: []
    autoincrement: false
    nullable: true
    primaryKey: false
  - name: "total_amount"
    typeName: "float"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 17
    scale: 17
    precision: 17
    columnProperties: []
    autoincrement: false
    nullable: true
    primaryKey: false
views: []
databaseProductName: "PostgreSQL"
databaseType: "kinetica"
operationLevel: "schema"
