---
safeMode: false
tables:
- name: "customers"
  type: "TABLE"
  schema: "nuhibesimi_gmail"
  columns:
  - name: "customer_id"
    typeName: "integer"
    ordinalPosition: 0
    primaryKeySequenceId: 1
    columnDisplaySize: 10
    scale: 0
    precision: 10
    columnProperties: []
    autoincrement: false
    nullable: false
    primaryKey: true
  - name: "first_name"
    typeName: "string"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 1000000000
    scale: 0
    precision: 1000000000
    columnProperties: []
    autoincrement: false
    nullable: false
    primaryKey: false
  - name: "last_name"
    typeName: "string"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 1000000000
    scale: 0
    precision: 1000000000
    columnProperties: []
    autoincrement: false
    nullable: false
    primaryKey: false
  - name: "email"
    typeName: "string"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 1000000000
    scale: 0
    precision: 1000000000
    columnProperties: []
    autoincrement: false
    nullable: false
    primaryKey: false
  - name: "phone"
    typeName: "string"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 1000000000
    scale: 0
    precision: 1000000000
    columnProperties: []
    autoincrement: false
    nullable: true
    primaryKey: false
  - name: "created_at"
    typeName: "datetime"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 23
    scale: 6
    precision: 23
    columnProperties: []
    autoincrement: false
    nullable: true
    primaryKey: false
- name: "nyctaxi"
  type: "TABLE"
  schema: "nuhibesimi_gmail"
  columns:
  - name: "vendor_id"
    typeName: "string"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 1000000000
    scale: 0
    precision: 1000000000
    columnProperties: []
    autoincrement: false
    nullable: true
    primaryKey: false
  - name: "pickup_datetime"
    typeName: "datetime"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 23
    scale: 6
    precision: 23
    columnProperties: []
    autoincrement: false
    nullable: true
    primaryKey: false
  - name: "dropoff_datetime"
    typeName: "datetime"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 23
    scale: 6
    precision: 23
    columnProperties: []
    autoincrement: false
    nullable: true
    primaryKey: false
  - name: "passenger_count"
    typeName: "integer"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 10
    scale: 0
    precision: 10
    columnProperties: []
    autoincrement: false
    nullable: true
    primaryKey: false
  - name: "trip_distance"
    typeName: "float"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 17
    scale: 17
    precision: 17
    columnProperties: []
    autoincrement: false
    nullable: true
    primaryKey: false
  - name: "pickup_longitude"
    typeName: "float"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 17
    scale: 17
    precision: 17
    columnProperties: []
    autoincrement: false
    nullable: true
    primaryKey: false
  - name: "pickup_latitude"
    typeName: "float"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 17
    scale: 17
    precision: 17
    columnProperties: []
    autoincrement: false
    nullable: true
    primaryKey: false
  - name: "rate_code_id"
    typeName: "integer"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 10
    scale: 0
    precision: 10
    columnProperties: []
    autoincrement: false
    nullable: true
    primaryKey: false
  - name: "store_and_fwd_flag"
    typeName: "string"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 1000000000
    scale: 0
    precision: 1000000000
    columnProperties: []
    autoincrement: false
    nullable: true
    primaryKey: false
  - name: "dropoff_longitude"
    typeName: "float"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 17
    scale: 17
    precision: 17
    columnProperties: []
    autoincrement: false
    nullable: true
    primaryKey: false
  - name: "dropoff_latitude"
    typeName: "float"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 17
    scale: 17
    precision: 17
    columnProperties: []
    autoincrement: false
    nullable: true
    primaryKey: false
  - name: "payment_type"
    typeName: "string"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 1000000000
    scale: 0
    precision: 1000000000
    columnProperties: []
    autoincrement: false
    nullable: true
    primaryKey: false
  - name: "fare_amount"
    typeName: "float"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 17
    scale: 17
    precision: 17
    columnProperties: []
    autoincrement: false
    nullable: true
    primaryKey: false
  - name: "surcharge"
    typeName: "float"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 17
    scale: 17
    precision: 17
    columnProperties: []
    autoincrement: false
    nullable: true
    primaryKey: false
  - name: "mta_tax"
    typeName: "float"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 17
    scale: 17
    precision: 17
    columnProperties: []
    autoincrement: false
    nullable: true
    primaryKey: false
  - name: "tip_amount"
    typeName: "float"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 17
    scale: 17
    precision: 17
    columnProperties: []
    autoincrement: false
    nullable: true
    primaryKey: false
  - name: "tolls_amount"
    typeName: "float"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 17
    scale: 17
    precision: 17
    columnProperties: []
    autoincrement: false
    nullable: true
    primaryKey: false
  - name: "total_amount"
    typeName: "float"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 17
    scale: 17
    precision: 17
    columnProperties: []
    autoincrement: false
    nullable: true
    primaryKey: false
  - name: "cab_type"
    typeName: "integer"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 10
    scale: 0
    precision: 10
    columnProperties: []
    autoincrement: false
    nullable: true
    primaryKey: false
- name: "payments"
  type: "TABLE"
  schema: "nuhibesimi_gmail"
  columns:
  - name: "payment_id"
    typeName: "integer"
    ordinalPosition: 0
    primaryKeySequenceId: 1
    columnDisplaySize: 10
    scale: 0
    precision: 10
    columnProperties: []
    autoincrement: false
    nullable: false
    primaryKey: true
  - name: "customer_id"
    typeName: "integer"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 10
    scale: 0
    precision: 10
    columnProperties: []
    foreignKeys:
    - name: "payments_customer_id_fkey"
      schema: "nuhibesimi_gmail"
      tableName: "payments"
      columnName: "customer_id"
      deleteRule: "3"
      primaryTableSchema: "public"
      primaryTableName: "customers"
      primaryColumnName: "customer_id"
    autoincrement: false
    nullable: false
    primaryKey: false
  - name: "amount"
    typeName: "double"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 17
    scale: 2
    precision: 17
    columnProperties: []
    autoincrement: false
    nullable: false
    primaryKey: false
  - name: "payment_date"
    typeName: "date"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 10
    scale: 0
    precision: 10
    columnProperties: []
    autoincrement: false
    nullable: false
    primaryKey: false
  - name: "payment_method"
    typeName: "string"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 1000000000
    scale: 0
    precision: 1000000000
    columnProperties: []
    autoincrement: false
    nullable: false
    primaryKey: false
- name: "playing_with_neon"
  type: "TABLE"
  schema: "nuhibesimi_gmail"
  columns:
  - name: "id"
    typeName: "integer"
    ordinalPosition: 0
    primaryKeySequenceId: 1
    columnDisplaySize: 10
    scale: 0
    precision: 10
    columnProperties: []
    autoincrement: false
    nullable: false
    primaryKey: true
  - name: "name"
    typeName: "string"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 1000000000
    scale: 0
    precision: 1000000000
    columnProperties: []
    autoincrement: false
    nullable: false
    primaryKey: false
  - name: "value"
    typeName: "float"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 8
    scale: 8
    precision: 8
    columnProperties: []
    autoincrement: false
    nullable: true
    primaryKey: false
views: []
databaseProductName: "PostgreSQL"
databaseType: "kinetica"
operationLevel: "schema"
