---
safeMode: false
tables:
- name: "customers"
  type: "TABLE"
  schema: "nuhibesimi_gmail"
  indices: []
  columns:
  - name: "customer_id"
    typeName: "integer"
    ordinalPosition: 0
    primaryKeySequenceId: 1
    columnDisplaySize: 10
    scale: 10
    precision: 10
    columnProperties: []
    autoincrement: false
    nullable: false
    primaryKey: true
  - name: "first_name"
    typeName: "string"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 1000000000
    scale: 0
    precision: 1000000000
    columnProperties: []
    autoincrement: false
    nullable: false
    primaryKey: false
  - name: "last_name"
    typeName: "string"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 1000000000
    scale: 0
    precision: 1000000000
    columnProperties: []
    autoincrement: false
    nullable: false
    primaryKey: false
  - name: "email"
    typeName: "string"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 1000000000
    scale: 0
    precision: 1000000000
    columnProperties: []
    autoincrement: false
    nullable: false
    primaryKey: false
  - name: "phone"
    typeName: "string"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 1000000000
    scale: 0
    precision: 1000000000
    columnProperties: []
    autoincrement: false
    nullable: true
    primaryKey: false
  - name: "created_at"
    typeName: "datetime"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 23
    scale: 0
    precision: 23
    columnProperties: []
    autoincrement: false
    nullable: true
    primaryKey: false
- name: "payments"
  type: "TABLE"
  schema: "nuhibesimi_gmail"
  indices: []
  columns:
  - name: "payment_id"
    typeName: "integer"
    ordinalPosition: 0
    primaryKeySequenceId: 1
    columnDisplaySize: 10
    scale: 10
    precision: 10
    columnProperties: []
    autoincrement: false
    nullable: false
    primaryKey: true
  - name: "customer_id"
    typeName: "integer"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 10
    scale: 10
    precision: 10
    columnProperties: []
    autoincrement: false
    nullable: false
    primaryKey: false
  - name: "amount"
    typeName: "double"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 17
    scale: 16
    precision: 17
    columnProperties: []
    autoincrement: false
    nullable: false
    primaryKey: false
  - name: "payment_date"
    typeName: "date"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 10
    scale: 0
    precision: 10
    columnProperties: []
    autoincrement: false
    nullable: false
    primaryKey: false
  - name: "payment_method"
    typeName: "string"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 1000000000
    scale: 0
    precision: 1000000000
    columnProperties: []
    autoincrement: false
    nullable: false
    primaryKey: false
- name: "playing_with_neon"
  type: "TABLE"
  schema: "nuhibesimi_gmail"
  indices: []
  columns:
  - name: "id"
    typeName: "integer"
    ordinalPosition: 0
    primaryKeySequenceId: 1
    columnDisplaySize: 10
    scale: 10
    precision: 10
    columnProperties: []
    autoincrement: false
    nullable: false
    primaryKey: true
  - name: "name"
    typeName: "string"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 1000000000
    scale: 0
    precision: 1000000000
    columnProperties: []
    autoincrement: false
    nullable: false
    primaryKey: false
  - name: "value"
    typeName: "REAL"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 8
    scale: 7
    precision: 8
    columnProperties: []
    autoincrement: false
    nullable: true
    primaryKey: false
views: []
databaseProductName: "Kinetica"
databaseType: "kinetica"
operationLevel: "schema"
