---
safeMode: false
tables:
- name: "customers"
  type: "TABLE"
  schema: "public"
  indices:
  - name: "customers_pkey"
    schema: "public"
    tableName: "customers"
    columnNames:
    - "customer_id"
    nonUnique: false
    type: 3
    ascOrDesc: "A"
    cardinality: 0
  - name: "customers_email_key"
    schema: "public"
    tableName: "customers"
    columnNames:
    - "email"
    nonUnique: false
    type: 3
    ascOrDesc: "A"
    cardinality: 0
  columns:
  - name: "customer_id"
    typeName: "serial"
    ordinalPosition: 0
    primaryKeySequenceId: 1
    columnDisplaySize: 10
    scale: 0
    precision: 10
    columnProperties: []
    nullable: false
    primaryKey: true
    autoincrement: false
  - name: "first_name"
    typeName: "varchar"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 50
    scale: 0
    precision: 50
    columnProperties: []
    nullable: false
    primaryKey: false
    autoincrement: false
  - name: "last_name"
    typeName: "varchar"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 50
    scale: 0
    precision: 50
    columnProperties: []
    nullable: false
    primaryKey: false
    autoincrement: false
  - name: "email"
    typeName: "varchar"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 100
    scale: 0
    precision: 100
    columnProperties: []
    nullable: false
    primaryKey: false
    autoincrement: false
  - name: "phone"
    typeName: "varchar"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 20
    scale: 0
    precision: 20
    columnProperties: []
    nullable: true
    primaryKey: false
    autoincrement: false
  - name: "created_at"
    typeName: "timestamp"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 29
    scale: 6
    precision: 29
    columnProperties: []
    nullable: true
    primaryKey: false
    autoincrement: false
- name: "nyctaxi"
  type: "TABLE"
  schema: "public"
  indices: []
  columns:
  - name: "vendor_id"
    typeName: "varchar"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 10
    scale: 0
    precision: 10
    columnProperties: []
    nullable: true
    primaryKey: false
    autoincrement: false
  - name: "pickup_datetime"
    typeName: "timestamp"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 29
    scale: 6
    precision: 29
    columnProperties: []
    nullable: true
    primaryKey: false
    autoincrement: false
  - name: "dropoff_datetime"
    typeName: "timestamp"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 29
    scale: 6
    precision: 29
    columnProperties: []
    nullable: true
    primaryKey: false
    autoincrement: false
  - name: "passenger_count"
    typeName: "int4"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 10
    scale: 0
    precision: 10
    columnProperties: []
    nullable: true
    primaryKey: false
    autoincrement: false
  - name: "trip_distance"
    typeName: "float8"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 17
    scale: 17
    precision: 17
    columnProperties: []
    nullable: true
    primaryKey: false
    autoincrement: false
  - name: "pickup_longitude"
    typeName: "float8"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 17
    scale: 17
    precision: 17
    columnProperties: []
    nullable: true
    primaryKey: false
    autoincrement: false
  - name: "pickup_latitude"
    typeName: "float8"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 17
    scale: 17
    precision: 17
    columnProperties: []
    nullable: true
    primaryKey: false
    autoincrement: false
  - name: "rate_code_id"
    typeName: "int4"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 10
    scale: 0
    precision: 10
    columnProperties: []
    nullable: true
    primaryKey: false
    autoincrement: false
  - name: "store_and_fwd_flag"
    typeName: "bpchar"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 1
    scale: 0
    precision: 1
    columnProperties: []
    nullable: true
    primaryKey: false
    autoincrement: false
  - name: "dropoff_longitude"
    typeName: "float8"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 17
    scale: 17
    precision: 17
    columnProperties: []
    nullable: true
    primaryKey: false
    autoincrement: false
  - name: "dropoff_latitude"
    typeName: "float8"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 17
    scale: 17
    precision: 17
    columnProperties: []
    nullable: true
    primaryKey: false
    autoincrement: false
  - name: "payment_type"
    typeName: "varchar"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 10
    scale: 0
    precision: 10
    columnProperties: []
    nullable: true
    primaryKey: false
    autoincrement: false
  - name: "fare_amount"
    typeName: "float8"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 17
    scale: 17
    precision: 17
    columnProperties: []
    nullable: true
    primaryKey: false
    autoincrement: false
  - name: "surcharge"
    typeName: "float8"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 17
    scale: 17
    precision: 17
    columnProperties: []
    nullable: true
    primaryKey: false
    autoincrement: false
  - name: "mta_tax"
    typeName: "float8"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 17
    scale: 17
    precision: 17
    columnProperties: []
    nullable: true
    primaryKey: false
    autoincrement: false
  - name: "tip_amount"
    typeName: "float8"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 17
    scale: 17
    precision: 17
    columnProperties: []
    nullable: true
    primaryKey: false
    autoincrement: false
  - name: "tolls_amount"
    typeName: "float8"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 17
    scale: 17
    precision: 17
    columnProperties: []
    nullable: true
    primaryKey: false
    autoincrement: false
  - name: "total_amount"
    typeName: "float8"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 17
    scale: 17
    precision: 17
    columnProperties: []
    nullable: true
    primaryKey: false
    autoincrement: false
  - name: "cab_type"
    typeName: "int4"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 10
    scale: 0
    precision: 10
    columnProperties: []
    nullable: true
    primaryKey: false
    autoincrement: false
- name: "payments"
  type: "TABLE"
  schema: "public"
  indices:
  - name: "payments_pkey"
    schema: "public"
    tableName: "payments"
    columnNames:
    - "payment_id"
    nonUnique: false
    type: 3
    ascOrDesc: "A"
    cardinality: 0
  columns:
  - name: "payment_id"
    typeName: "serial"
    ordinalPosition: 0
    primaryKeySequenceId: 1
    columnDisplaySize: 10
    scale: 0
    precision: 10
    columnProperties: []
    nullable: false
    primaryKey: true
    autoincrement: false
  - name: "customer_id"
    typeName: "int4"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 10
    scale: 0
    precision: 10
    columnProperties: []
    foreignKeys:
    - name: "payments_customer_id_fkey"
      schema: "public"
      tableName: "payments"
      columnName: "customer_id"
      deleteRule: "3"
      primaryTableSchema: "public"
      primaryTableName: "customers"
      primaryColumnName: "customer_id"
    nullable: false
    primaryKey: false
    autoincrement: false
  - name: "amount"
    typeName: "numeric"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 10
    scale: 2
    precision: 10
    columnProperties: []
    nullable: false
    primaryKey: false
    autoincrement: false
  - name: "payment_date"
    typeName: "date"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 13
    scale: 0
    precision: 13
    columnProperties: []
    nullable: false
    primaryKey: false
    autoincrement: false
  - name: "payment_method"
    typeName: "varchar"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 20
    scale: 0
    precision: 20
    columnProperties: []
    nullable: false
    primaryKey: false
    autoincrement: false
views: []
databaseProductName: "PostgreSQL"
databaseType: "postgres"
operationLevel: "schema"
