---
safeMode: false
tables:
- name: "nyctaxi"
  type: "TABLE"
  schema: "public"
  indices: []
  columns:
  - name: "vendor_id"
    typeName: "varchar"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 10
    scale: 0
    precision: 10
    columnProperties: []
    primaryKey: false
    nullable: true
    autoincrement: false
  - name: "pickup_datetime"
    typeName: "timestamp"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 29
    scale: 6
    precision: 29
    columnProperties: []
    primaryKey: false
    nullable: true
    autoincrement: false
  - name: "dropoff_datetime"
    typeName: "timestamp"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 29
    scale: 6
    precision: 29
    columnProperties: []
    primaryKey: false
    nullable: true
    autoincrement: false
  - name: "passenger_count"
    typeName: "int4"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 10
    scale: 0
    precision: 10
    columnProperties: []
    primaryKey: false
    nullable: true
    autoincrement: false
  - name: "trip_distance"
    typeName: "float8"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 17
    scale: 17
    precision: 17
    columnProperties: []
    primaryKey: false
    nullable: true
    autoincrement: false
  - name: "pickup_longitude"
    typeName: "float8"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 17
    scale: 17
    precision: 17
    columnProperties: []
    primaryKey: false
    nullable: true
    autoincrement: false
  - name: "pickup_latitude"
    typeName: "float8"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 17
    scale: 17
    precision: 17
    columnProperties: []
    primaryKey: false
    nullable: true
    autoincrement: false
  - name: "rate_code_id"
    typeName: "int4"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 10
    scale: 0
    precision: 10
    columnProperties: []
    primaryKey: false
    nullable: true
    autoincrement: false
  - name: "store_and_fwd_flag"
    typeName: "bpchar"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 1
    scale: 0
    precision: 1
    columnProperties: []
    primaryKey: false
    nullable: true
    autoincrement: false
  - name: "dropoff_longitude"
    typeName: "float8"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 17
    scale: 17
    precision: 17
    columnProperties: []
    primaryKey: false
    nullable: true
    autoincrement: false
  - name: "dropoff_latitude"
    typeName: "float8"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 17
    scale: 17
    precision: 17
    columnProperties: []
    primaryKey: false
    nullable: true
    autoincrement: false
  - name: "payment_type"
    typeName: "varchar"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 10
    scale: 0
    precision: 10
    columnProperties: []
    primaryKey: false
    nullable: true
    autoincrement: false
  - name: "fare_amount"
    typeName: "float8"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 17
    scale: 17
    precision: 17
    columnProperties: []
    primaryKey: false
    nullable: true
    autoincrement: false
  - name: "surcharge"
    typeName: "float8"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 17
    scale: 17
    precision: 17
    columnProperties: []
    primaryKey: false
    nullable: true
    autoincrement: false
  - name: "mta_tax"
    typeName: "float8"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 17
    scale: 17
    precision: 17
    columnProperties: []
    primaryKey: false
    nullable: true
    autoincrement: false
  - name: "tip_amount"
    typeName: "float8"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 17
    scale: 17
    precision: 17
    columnProperties: []
    primaryKey: false
    nullable: true
    autoincrement: false
  - name: "tolls_amount"
    typeName: "float8"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 17
    scale: 17
    precision: 17
    columnProperties: []
    primaryKey: false
    nullable: true
    autoincrement: false
  - name: "total_amount"
    typeName: "float8"
    ordinalPosition: 0
    primaryKeySequenceId: 0
    columnDisplaySize: 17
    scale: 17
    precision: 17
    columnProperties: []
    primaryKey: false
    nullable: true
    autoincrement: false
views: []
databaseProductName: "PostgreSQL"
databaseType: "postgres"
operationLevel: "schema"
