name: main

on:
  push:
    branches:
      - main
  #schedule:
  #  - cron: '*/15 * * * *' #every 15 minutes

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  rosetta-schema-migration:
    name: "Rosetta: Schema Migration"
    runs-on: ubuntu-latest

    env:
      POSTGRES_HOST: ${{ vars.POSTGRES_HOST }}
      POSTGRES_USER: ${{ vars.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ vars.POSTGRES_DB }}
      SOURCE_SCHEMA: ${{ vars.SOURCE_SCHEMA }}
      KINETICA_URL: ${{ vars.KINETICA_URL }}
      KINETICA_USER: ${{ vars.KINETICA_USER }}
      KINETICA_PASSWORD: ${{ secrets.KINETICA_PASSWORD }}
      TARGET_SCHEMA: ${{ vars.TARGET_SCHEMA }}

    steps:
      - uses: actions/checkout@v4
      - run: |
          git pull origin main

      - name: rosetta init
        run: './scripts/rosetta_init.sh'
        shell: bash

      - name: rosetta compile
        run: 'SOURCE_SCHEMA=${{vars.SOURCE_SCHEMA}} TARGET_SCHEMA=${{vars.TARGET_SCHEMA}} ./scripts/rosetta_compile.sh'
        shell: bash

      - name: rosetta apply
        run: 'SOURCE_SCHEMA=${{vars.SOURCE_SCHEMA}} TARGET_SCHEMA=${{vars.TARGET_SCHEMA}} KINETICA_PASSWORD=${{secrets.KINETICA_PASSWORD}} ./scripts/rosetta_apply.sh'
        shell: bash

      - name: Commit changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git pull origin main
          git add .
          git commit -m "Schema changes"
        continue-on-error: true

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
        run: |
          git push origin main

  kisql-load-data:
    name: "Kinetica: Data Load"
    runs-on: ubuntu-latest
    needs: rosetta-schema-migration

    env:
      KINETICA_URL: ${{ vars.KINETICA_URL }}
      KINETICA_USER: ${{ vars.KINETICA_USER }}
      KINETICA_PASSWORD: ${{ secrets.KINETICA_PASSWORD }}
      TARGET_SCHEMA: ${{ vars.TARGET_SCHEMA }}
      
    steps:
      - uses: actions/checkout@v4
      - run: |
          git pull origin main

      - name: kinetica load
        run: 'KINETICA_USER=${{vars.KINETICA_USER}} KINETICA_PASSWORD=${{secrets.KINETICA_PASSWORD}} ./scripts/kisql_load_data.sh'
        shell: bash

  rosetta-data-quality-check:
    name: "Rosetta: Data Quality Check"
    runs-on: ubuntu-latest
    needs: kisql-load-data

    env:
      KINETICA_URL: ${{ vars.KINETICA_URL }}
      KINETICA_USER: ${{ vars.KINETICA_USER }}
      KINETICA_PASSWORD: ${{ secrets.KINETICA_PASSWORD }}
      TARGET_SCHEMA: ${{ vars.TARGET_SCHEMA }}

    steps:
      - uses: actions/checkout@v4
      - run: |
          git pull origin main

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml
      
      - name: rosetta add tests
        run: 'python scripts/rosetta_add_tests.py kinetica-cloud/model.yaml tests.csv'
        shell: bash

      - name: rosetta test
        run: 'KINETICA_PASSWORD=${{secrets.KINETICA_PASSWORD}} ./scripts/rosetta_test.sh'
        shell: bash

      - name: Commit changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git pull origin main
          git add .
          git commit -m "Added tests for data quality check"
        continue-on-error: true

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
        run: |
          git push origin main
